### ISSUE TITLE
help!shinyserver can't work

### ISSUE THREAD

**Issue by GODCALLMEGOD** [vallotlab/ChromSCape#18]
dear author:
     I very love your package after reading your paper concerning scCUT&TAG and scCHIP-seq. But I can't use launchApp(), though I change my IP, it only sent me the same error.
`The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Customizing AdminLTE blue skin with the current {fresh} theme
Warning in sub(" *\\r$", "", volNames) :
' to a wide stringate '<d0>¼Ӿ<ed>       
Warning: Error in sub: input string 4 is invalid
  41: sub
  40: shinyFiles::getVolumes()
  39: server [C:\Users\win11\AppData\Local\R\win-library\4.3\ChromSCape/server.R#14]
   2: shiny::runApp
   1: launchApp
Error in sub(" *\\r$", "", volNames) : input string 4 is invalid`

**Comment by Pacomito** [comment]
Dear God, 
Thank you for your message, 
The first message is a warning and should not be of any harm.

I think the error comes from the use of non english characters on windows by shinyFiles (https://github.com/thomasp85/shinyFiles/issues/165) and eventually the fs package (https://github.com/r-lib/fs/issues/366). 

However this should be fixed in package fs > 1.6.2. Please close and reopen R/Rstudio and  run :
`install.packages("fs")` 
Then try again :
 `library(ChromSCape); launchApp()`

**Comment by GODCALLMEGOD** [comment]
> 亲爱的上帝，谢谢你的信息，第一条信息是一个警告，不应该有任何伤害。
> 
> 我认为错误来自 shinyFiles （[thomasp85/shinyFiles#165](https://github.com/thomasp85/shinyFiles/issues/165)） 在 Windows 上使用非英文字符，最终是 fs 包 （[r-lib/fs#366](https://github.com/r-lib/fs/issues/366)）。
> 
> 但是，这应该在 fs > 1.6.2 包中修复。请关闭并重新打开 R/Rstudio 并运行：然后重试：`install.packages("fs")` `library(ChromSCape); launchApp()`

Thanks for your remind, now I can launch it in WSL2, and I love it to death! what a great creation! You are the tutors guiding human to search the Biological truth, give my best wishes to you!

**Comment by Pacomito** [comment]
Good to hear you managed to launch it, 
Best,
Pacome
