### ISSUE TITLE
Problems loading fragments file

### ISSUE THREAD

**Issue by A-legac45** [vallotlab/ChromSCape#7]
I am Anne-laure Le Gac woriking on the EPIMAIT project from olivier teams.
I have a problem when I want to load my fragments.tsv.gz file

warning : can't find any specified file types in the upload folder

Do you know how to manage this problem?

**Comment by Pacomito** [comment]
Hello Anne-Laure,

This might be because your folder is not organised in a way that ChromSCape can recognise or that you mis-selected the base directory.

I will show an example with images:

1. Here is an example of organised folder for fragment files (this is the same for Sparse Matrix & Single-Cell BED inputs):  
  
![example_fragment_file_3](https://user-images.githubusercontent.com/36704054/193560613-d04cce4d-6064-4f72-b3a6-3458073e72ce.png)
  
  Note that **each sample is placed in its own folder** (e.g. *GBM_H3K27me3*) containing the fragment file and it's index (optional). **All the folders are placed in the same directory** (e.g.  *Fragments/*), which **is the directory you have to select in ChromSCape**.
  
2. In ChromSCape, tick the **'Fragment File'** input data type and click on the button **'Select  folder containing raw files'**
  
![example_fragment_file_1](https://user-images.githubusercontent.com/36704054/193561794-7eaf5369-69f9-43ce-8966-e96eb0141805.png)

3. Then select the base directory *'Fragments'* and click on **'Select'**
  
![example_fragment_file_2](https://user-images.githubusercontent.com/36704054/193568258-0d08b485-8ea6-4e18-a577-f4befee3e9df.png)

4. Finally, remove the unwanted samples by clicking in the **'Selected samples'** area and removing samples with the backspace key, and click on **'Create Analysis'**
  
![example_fragment_file_4](https://user-images.githubusercontent.com/36704054/193569511-0133ed9c-38aa-4f6b-bbe8-9d190d13dbcd.png)
